### ISSUE TITLE
akiyamarkdownチートシート

### ISSUE THREAD

**Issue by nokakiyama** [KazIgu/akiyamarkdown#4]
こんな感じでYolo
#### akiyamarkdownインストール手順

【Akiyamarkdown概要】
■Akiyamarkdownとは
・秋山の手癖によって誕生したメモ書きの記法である。
　→これといった利点は特に無い。

■インストール手順
・Akiyamarkdown.zipをデスクトップに解凍
・ターミナルで下記を実行
　→mv Desktop/Akiyamarkdown ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/
　　→更新（新しいAkiyamarkdown.zipをインストール）する際には先に下記を実行してから上記を実行すること！
　　　→rm -rf ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/Akiyamarkdown

　※sublime text3の場合は上記「Sublime\ Text\ 2」部分を「Sublime\ Text\ 3」にすること

■ルール
・大見出し
　→「【】」
・中見出し
　→「■」
・小見出し
　→「・」
・インデント
　→「→」

■ショートカットキー
・大見出し召喚
　→「+tab
・中見出し召喚
　→■+tab
・インデント召喚
　→ー+tab
・よしなに改行
　→shift+enter
　　→大見出し時にshift+enter
　　　→自動で中見出し召喚
　　→中見出し時にshift+enter
　　　→自動で小見出し召喚
　　→小見出し時にshift+enter
　　　→自動で小見出し召喚
　　　　→その後spaceでインデント召喚
　　→インデント時にshift+enter
　　　→自動で同じ階層にインデント召喚
　　　　→その後spaceでさらに一行右にインデント可能
・日付入力
　→command+shift+D
　　→yyyymmddで入力
・インデント中の改行
　→command+option+enter
　　→たとえば
　　　こういうこと
　　　→この状態でshift+enterすると同じ階層にインデント召喚
・上の行と同じところまでインデント
　→shift+tab

■なにができるの？
・別になにもできないよ！
　→秋山がメモ書きしやすくなるだけだよ！
　　→今後この記法をベースに、リアルタイムにツリー図が作成されるツールを開発予定だよ！

■だれが作ったの？
・記法は秋山の手癖だよ！
・sublimeのプラグイン化してsyntax含め色々やってくれたのは井口くんだよ！

**Comment by KazIgu** [comment]
https://github.com/KazIgu/akiyamarkdown/wiki/akiyamarkdown%E3%83%81%E3%83%BC%E3%83%88%E3%82%B7%E3%83%BC%E3%83%88
wikiに移動した
